---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  ansible_connection: ssh
  ansible_sudo: false
  ansible_verbose: true
  ansible_verbosity: 3
  require_chef_for_busser: false

platforms:
  - name: centos-7.3
    driver_config:
      privileged: true
      run_command: /sbin/init

verifier:
  name: serverspec
  patterns:
    - roles/ansible-role-docker/test/integration/default/serverspec/*_spec.rb
  env_vars:
    TARGET_HOST: localhost
    LOGIN_USER: kitchen
    SSH_KEY: 'roles/ansible-role-docker/.kitchen/docker_id_rsa'

suites:
  - name: default
