---

- when: ansible_distribution == "CentOS"
  block:
    - when: ansible_distribution_major_version == "7"
      block:
        - set_fact:
            version_suffix: ".ce-1.el7.centos"

- name: install dependencies
  yum:
    name: "{{item}}"
  with_items: "{{ docker_dependencies }}"

- name: set up yum repository
  command: yum-config-manager --add-repo {{docker_yum_repository_url}}
  args:
    creates: /etc/yum.repos.d/{{docker_yum_repository_url | basename}}

- name: install docker
  yum:
    name: docker-ce-{{docker_version}}{{version_suffix}}

- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes
